/**
 * art/basis.js — The first fifteen followers.
 *
 * Grids are 12x12, one or two frames (two = an idle loop; one = it just bobs).
 * Rows may be short or missing; the renderer pads them out. Chars index the
 * shared PALETTE in ./palette.js.
 */

export const BASIS = {
  ghost: [[
    '............',
    '....WW......',
    '...WWWWWW...',
    '..wWWWWWWW..',
    '..wWLEWLEW..',
    '..wWEEWEEW..',
    '..wWWWWWWW..',
    '..wWWWWWWW..',
    '..wwwwwwww..',
    '..WW..WW.W..',
  ], [
    '............',
    '....WW......',
    '...WWWWWW...',
    '..wWWWWWWW..',
    '..wWLEWLEW..',
    '..wWEEWEEW..',
    '..wWWWWWWW..',
    '..wWWWWWWW..',
    '..wwwwwwww..',
    '..WWW..WW...',
  ]],

  drone: [[
    '............',
    '............',
    '.LLLSSSSSSS.',
    '......D.....',
    '...SSSSSS...',
    '...DKRRKD...',
    '...DKKKKD...',
    '...DDDDDD...',
    '...KKKKKK...',
    '...K....K...',
    '...K....K...',
  ], [
    '............',
    '............',
    '.SSSSSSSLLL.',
    '......D.....',
    '...SSSSSS...',
    '...DKYYKD...',
    '...DKKKKD...',
    '...DDDDDD...',
    '...KKKKKK...',
    '...K....K...',
    '...K....K...',
  ]],

  papegaai: [[
    '............',
    '.....RRR....',
    '....RRRRR...',
    '....RKRRRY..',
    '....RRRRYY..',
    '..GRRRRRR...',
    '.GGBBRRRR...',
    '..GBBBRRR...',
    '...GBBRRR...',
    '.....YY.....',
  ], [
    '............',
    '.....RRR....',
    '....RRRRR...',
    '....RKRRRY..',
    '....RRRRYY..',
    '..GRRRRRR...',
    '.GGCCRRRR...',
    '..GCCBRRR...',
    '...GCBRRR...',
    '.....YY.....',
  ]],

  // Wings up / wings down — a firebird, not a fireball.
  feniks: [[
    '............',
    '...O....O...',
    '..OYO..OYO..',
    '..OYYO.OYYO.',
    '.OOYYYOYYYO.',
    '.OYYYYYYYKO.',
    '.OYYYYYYYO..',
    '..OOYYYOO...',
    '...O.O.O....',
  ], [
    '............',
    '............',
    '..O......O..',
    '..OYO..OYO..',
    '.OOYYYOYYYO.',
    '.OYYYYYYYKO.',
    '.OYYYYYYYO..',
    '..OYYYYYO...',
    '..OOYYYOO...',
    '...OO.OO....',
  ]],

  ufo: [[
    '............',
    '............',
    '....CCCC....',
    '...CWWWWC...',
    '..SSSSSSSS..',
    '.SYSSRSSYSS.',
    '.SSSSSSSSSS.',
    '..S.C..C.S..',
    '....C..C....',
  ], [
    '............',
    '............',
    '....CCCC....',
    '...CWWWWC...',
    '..SSSSSSSS..',
    '.SRSSYSSRSS.',
    '.SSSSSSSSSS.',
    '..S..CC..S..',
    '.....CC.....',
  ]],

  vliegtuig: [[
    '............',
    '............',
    '..W.......S.',
    '..WW......S.',
    '.WWWWWWWWWS.',
    '.WWWWWWWWWS.',
    '..BBBBB...S.',
    '...BBB....S.',
  ], [
    '............',
    '............',
    '..W.........',
    '..WW........',
    '.WWWWWWWWSSS',
    '.WWWWWWWWSSS',
    '..BBBBB.....',
    '...BBB......',
  ]],

  ballon: [[
    '............',
    '....RRRR....',
    '...RRRRRR...',
    '..RRLRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
    '.....RR.....',
    '.....K......',
    '......K.....',
    '.....K......',
  ], [
    '............',
    '....RRRR....',
    '...RRRRRR...',
    '..RRLRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
    '.....RR.....',
    '......K.....',
    '.....K......',
    '......K.....',
  ]],

  happertje: [[
    '............',
    '...YYYY.....',
    '..YYKYYY....',
    '.YYYYYYY....',
    '.YYYYYY.....',
    '.YYYYY......',
    '.YYYYYY.....',
    '.YYYYYYY....',
    '..YYYYYY....',
    '...YYYY.....',
  ], [
    '............',
    '...YYYY.....',
    '..YYKYYY....',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '..YYYYYY....',
    '...YYYY.....',
  ]],

  // The bulb stays a bulb; frame 2 only adds glow rays around it.
  lampje: [[
    '............',
    '....YYYY....',
    '...YYYYYY...',
    '...YLYYYY...',
    '...YYYYYY...',
    '....YYYY....',
    '....SSSS....',
    '....S..S....',
    '.....SS.....',
  ], [
    '.....L......',
    '..L.YYYY.L..',
    '...YYYYYY...',
    '..LYLYYYYL..',
    '...YYYYYY...',
    '..L.YYYY.L..',
    '....SSSS....',
    '....S..S....',
    '.....SS.....',
  ]],

  vlammetje: [[
    '............',
    '.....O......',
    '....OYO.....',
    '....OYYO....',
    '...OYYYO....',
    '...OYLYO....',
    '...OYYYO....',
    '....OOO.....',
  ], [
    '.....O......',
    '....OO......',
    '....OYO.....',
    '...OYYYO....',
    '...OYYYO....',
    '...OYLYO....',
    '...OOYOO....',
    '....OOO.....',
  ]],

  raket: [[
    '.....W......',
    '....WWW.....',
    '....WRW.....',
    '....WWW.....',
    '...WWWWW....',
    '...RW.WR....',
    '....OOO.....',
    '.....O......',
  ], [
    '.....W......',
    '....WWW.....',
    '....WRW.....',
    '....WWW.....',
    '...WWWWW....',
    '...RW.WR....',
    '....OOO.....',
    '....OYO.....',
    '.....O......',
  ]],

  sterretjes: [[
    '..Y.........',
    '.YYY....L...',
    '..Y....LLL..',
    '........L...',
    '............',
    '.....Y......',
    '....YYY.....',
    '.....Y......',
  ], [
    '..L.........',
    '.LLL....Y...',
    '..L....YYY..',
    '........Y...',
    '............',
    '.....L......',
    '....LLL.....',
    '.....L......',
  ]],

  paddestoel: [[
    '............',
    '...RRRRRR...',
    '..RRWRRWRR..',
    '.RRRRRRRRRR.',
    '.RWRRRRRRWR.',
    '.RRRRRRRRRR.',
    '..WWWWWWWW..',
    '...WKWWKW...',
    '...WWWWWW...',
    '...WWWWWW...',
  ], [
    '............',
    '...RRRRRR...',
    '..RRWRRWRR..',
    '.RRRRRRRRRR.',
    '.RWRRRRRRWR.',
    '.RRRRRRRRRR.',
    '..WWWWWWWW..',
    '...WWWWWW...',
    '...WWWWWW...',
    '...WWWWWW...',
  ]],

  appel: [[
    '............',
    '......N.....',
    '.....N.G....',
    '...RRRRRR...',
    '..RRRRRRRR..',
    '..RLRRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
  ], [
    '............',
    '......N.....',
    '.....NGG....',
    '...RRRRRR...',
    '..RRRRRRRR..',
    '..RLRRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
  ]],

  banaan: [[
    '............',
    '.......KK...',
    '......YYYY..',
    '.....YYYY...',
    '....YYYY....',
    '...YYYY.....',
    '..YYYY......',
    '..YYY.......',
    '..YYYY......',
    '...YYYY.....',
    '....YYY.....',
  ]],
};
