/**
 * art/dieren.js — Animals.
 *
 * The snail is the point of this file: its grid is unremarkable, but with a
 * huge `lag` in its catalog entry it permanently trails miles behind you and
 * never quite catches up. The joke is the movement, not the picture.
 */

export const DIEREN = {
  egeltje: [[
    '............',
    '..K.K.K.K...',
    '.KNKNKNKNK..',
    '.NNNNNNNNNN.',
    'NNNNNNNNNNNN',
    'NNNNNNNNNwww',
    'NNNNNNNNNwKw',
    '.NNNNNNNNwww',
    '.NNNNNNNNN..',
    '..N.NN.N....',
  ], [
    '............',
    '...K.K.K.K..',
    '.KNKNKNKNK..',
    '.NNNNNNNNNN.',
    'NNNNNNNNNNNN',
    'NNNNNNNNNwww',
    'NNNNNNNNNwKw',
    '.NNNNNNNNwww',
    '.NNNNNNNNN..',
    '...N.NN.N...',
  ]],

  uil: [[
    '............',
    '..N......N..',
    '..NN....NN..',
    '.NNNNNNNNNN.',
    '.NWWNNNNWWN.',
    '.NWKWNNWKWN.',
    '.NWWNYYNWWN.',
    '.NNNNYYNNNN.',
    '..NNNNNNNN..',
    '...NN..NN...',
    '....Y..Y....',
  ], [
    '............',
    '..N......N..',
    '..NN....NN..',
    '.NNNNNNNNNN.',
    '.NWWNNNNWWN.',
    '.NKKWNNWKKN.',
    '.NWWNYYNWWN.',
    '.NNNNYYNNNN.',
    '..NNNNNNNN..',
    '...NN..NN...',
    '....Y..Y....',
  ]],

  // Purple, not black: drawn in K it was invisible against the game's dark sky.
  vleermuis: [[
    '............',
    '..P......P..',
    '..PP....PP..',
    'PPPPPPPPPPPP',
    'PPPPRPPRPPPP',
    '.PPPPPPPPPP.',
    '..PPWPPWPP..',
    '...PPPPPP...',
    '....PPPP....',
  ], [
    '............',
    '............',
    '..P......P..',
    '..PP....PP..',
    '.PPPPPPPPPP.',
    '.PPPRPPRPPP.',
    '..PPPPPPPP..',
    '..PPWPPWPP..',
    '...PPPPPP...',
  ]],

  kikker: [[
    '............',
    '..GG....GG..',
    '.GWWG..GWWG.',
    '.GWKG..GWKG.',
    '.GGGGGGGGGG.',
    'GGGGGGGGGGGG',
    'GgGGGGGGGGgG',
    'GGgggggggGGG',
    '.GG.gggg.GG.',
    'GG........GG',
  ], [
    '............',
    '..GG....GG..',
    '.GWWG..GWWG.',
    '.GKWG..GKWG.',
    '.GGGGGGGGGG.',
    'GGGGGGGGGGGG',
    'GgGGGGGGGGgG',
    'GGgggggggGGG',
    '.GG.gggg.GG.',
    '.GG......GG.',
  ]],

  slak: [[
    '............',
    '..........K.',
    '.........K..',
    '..NNNN...N..',
    '.NYYYYN.NNN.',
    'NYYNNYYNNNNN',
    'NYNYYNYNNKNN',
    'NYYNNYYNNNNN',
    '.NYYYYN.NNNN',
    '..NNNN..NNNN',
    'wwwwwwwwwwww',
  ], [
    '............',
    '.........K..',
    '........K...',
    '..NNNN...N..',
    '.NYYYYN.NNN.',
    'NYYNNYYNNNNN',
    'NYNYYNYNNKNN',
    'NYYNNYYNNNNN',
    '.NYYYYN.NNNN',
    '..NNNN..NNNN',
    '.wwwwwwwwww.',
  ]],

  bijtje: [[
    '............',
    '..w..ww..w..',
    '..ww.ww.ww..',
    '...wwwwww...',
    '...YKYYKY...',
    '..YYKYYKYY..',
    '..YKKYYKKY..',
    '..YYKYYKYY..',
    '...YKYYKY...',
    '....KKKK....',
  ], [
    '............',
    '............',
    '...w....w...',
    '...wwwwww...',
    '...YKYYKY...',
    '..YYKYYKYY..',
    '..YKKYYKKY..',
    '..YYKYYKYY..',
    '...YKYYKY...',
    '....KKKK....',
  ]],

  pinguin: [[
    '............',
    '....KKKK....',
    '...KKKKKK...',
    '..KKWKKWKK..',
    '..KKKOOKKK..',
    '..KWWWWWWK..',
    '.KKWWWWWWKK.',
    '.KKWWWWWWKK.',
    '..KWWWWWWK..',
    '...KKWWKK...',
    '...OO..OO...',
  ], [
    '............',
    '....KKKK....',
    '...KKKKKK...',
    '..KKWKKWKK..',
    '..KKKOOKKK..',
    '.KKWWWWWWKK.',
    'KK.WWWWWW.KK',
    '.KKWWWWWWKK.',
    '..KWWWWWWK..',
    '...KKWWKK...',
    '...OO..OO...',
  ]],
};
