/**
 * follower-art.js — Follower sprites as data.
 *
 * A follower is a pixel grid, not a function: 12×12, one or two frames (two =
 * a 2-frame idle loop; one = it just bobs). Chars index the shared PALETTE
 * below, so a new follower is ONE entry here — no builder, no code, nowhere
 * else to touch.
 *
 * Rows may be short or missing; the renderer pads them out to 12×12.
 *
 * Palette (shared on purpose — it keeps the cast looking like one set):
 *   .  transparent   K  outline/black   W  white        w  white-shade
 *   R  red           r  dark red        O  orange       Y  yellow
 *   G  green         g  dark green      B  blue         b  dark blue
 *   C  cyan          P  purple          M  pink         N  brown
 *   S  silver        D  dark grey       E  eye-dark     L  glint/white-hot
 */

export const SIZE = 12;

export const PALETTE = {
  K: '#1a1a22', W: '#f0f4ff', w: '#a9cef0', R: '#e04030', r: '#a02818',
  O: '#ff8c1a', Y: '#ffd23f', G: '#4ac850', g: '#2a8a38', B: '#4a9ae0',
  b: '#2a5aa0', C: '#7fe8f0', P: '#a05ad0', M: '#f070b0', N: '#8a5a2a',
  S: '#9aa6b8', D: '#5a6472', E: '#26405c', L: '#ffffff',
};

export const FOLLOWER_ART = {
  ghost: [[
    '............',
    '....WW......',
    '...WWWWWW...',
    '..wWWWWWWW..',
    '..wWLEWLEW..',
    '..wWEEWEEW..',
    '..wWWWWWWW..',
    '..wWWWWWWW..',
    '..wwwwwwww..',
    '..WW..WW.W..',
  ], [
    '............',
    '....WW......',
    '...WWWWWW...',
    '..wWWWWWWW..',
    '..wWLEWLEW..',
    '..wWEEWEEW..',
    '..wWWWWWWW..',
    '..wWWWWWWW..',
    '..wwwwwwww..',
    '..WWW..WW...',
  ]],

  drone: [[
    '............',
    '............',
    '.LLLSSSSSSS.',
    '......D.....',
    '...SSSSSS...',
    '...DKRRKD...',
    '...DKKKKD...',
    '...DDDDDD...',
    '...KKKKKK...',
    '...K....K...',
    '...K....K...',
  ], [
    '............',
    '............',
    '.SSSSSSSLLL.',
    '......D.....',
    '...SSSSSS...',
    '...DKYYKD...',
    '...DKKKKD...',
    '...DDDDDD...',
    '...KKKKKK...',
    '...K....K...',
    '...K....K...',
  ]],

  papegaai: [[
    '............',
    '.....RRR....',
    '....RRRRR...',
    '....RKRRRY..',
    '....RRRRYY..',
    '..GRRRRRR...',
    '.GGBBRRRR...',
    '..GBBBRRR...',
    '...GBBRRR...',
    '.....YY.....',
  ], [
    '............',
    '.....RRR....',
    '....RRRRR...',
    '....RKRRRY..',
    '....RRRRYY..',
    '..GRRRRRR...',
    '.GGCCRRRR...',
    '..GCCBRRR...',
    '...GCBRRR...',
    '.....YY.....',
  ]],

  // Wings up / wings down — a firebird, not a fireball.
  feniks: [[
    '............',
    '...O....O...',
    '..OYO..OYO..',
    '..OYYO.OYYO.',
    '.OOYYYOYYYO.',
    '.OYYYYYYYKO.',
    '.OYYYYYYYO..',
    '..OOYYYOO...',
    '...O.O.O....',
  ], [
    '............',
    '............',
    '..O......O..',
    '..OYO..OYO..',
    '.OOYYYOYYYO.',
    '.OYYYYYYYKO.',
    '.OYYYYYYYO..',
    '..OYYYYYO...',
    '..OOYYYOO...',
    '...OO.OO....',
  ]],

  ufo: [[
    '............',
    '............',
    '....CCCC....',
    '...CWWWWC...',
    '..SSSSSSSS..',
    '.SYSSRSSYSS.',
    '.SSSSSSSSSS.',
    '..S.C..C.S..',
    '....C..C....',
  ], [
    '............',
    '............',
    '....CCCC....',
    '...CWWWWC...',
    '..SSSSSSSS..',
    '.SRSSYSSRSS.',
    '.SSSSSSSSSS.',
    '..S..CC..S..',
    '.....CC.....',
  ]],

  vliegtuig: [[
    '............',
    '............',
    '..W.......S.',
    '..WW......S.',
    '.WWWWWWWWWS.',
    '.WWWWWWWWWS.',
    '..BBBBB...S.',
    '...BBB....S.',
  ], [
    '............',
    '............',
    '..W.........',
    '..WW........',
    '.WWWWWWWWSSS',
    '.WWWWWWWWSSS',
    '..BBBBB.....',
    '...BBB......',
  ]],

  ballon: [[
    '............',
    '....RRRR....',
    '...RRRRRR...',
    '..RRLRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
    '.....RR.....',
    '.....K......',
    '......K.....',
    '.....K......',
  ], [
    '............',
    '....RRRR....',
    '...RRRRRR...',
    '..RRLRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
    '.....RR.....',
    '......K.....',
    '.....K......',
    '......K.....',
  ]],

  happertje: [[
    '............',
    '...YYYY.....',
    '..YYKYYY....',
    '.YYYYYYY....',
    '.YYYYYY.....',
    '.YYYYY......',
    '.YYYYYY.....',
    '.YYYYYYY....',
    '..YYYYYY....',
    '...YYYY.....',
  ], [
    '............',
    '...YYYY.....',
    '..YYKYYY....',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '.YYYYYYYY...',
    '..YYYYYY....',
    '...YYYY.....',
  ]],

  // The bulb stays a bulb; frame 2 only adds glow rays around it.
  lampje: [[
    '............',
    '....YYYY....',
    '...YYYYYY...',
    '...YLYYYY...',
    '...YYYYYY...',
    '....YYYY....',
    '....SSSS....',
    '....S..S....',
    '.....SS.....',
  ], [
    '.....L......',
    '..L.YYYY.L..',
    '...YYYYYY...',
    '..LYLYYYYL..',
    '...YYYYYY...',
    '..L.YYYY.L..',
    '....SSSS....',
    '....S..S....',
    '.....SS.....',
  ]],

  vlammetje: [[
    '............',
    '.....O......',
    '....OYO.....',
    '....OYYO....',
    '...OYYYO....',
    '...OYLYO....',
    '...OYYYO....',
    '....OOO.....',
  ], [
    '.....O......',
    '....OO......',
    '....OYO.....',
    '...OYYYO....',
    '...OYYYO....',
    '...OYLYO....',
    '...OOYOO....',
    '....OOO.....',
  ]],

  raket: [[
    '.....W......',
    '....WWW.....',
    '....WRW.....',
    '....WWW.....',
    '...WWWWW....',
    '...RW.WR....',
    '....OOO.....',
    '.....O......',
  ], [
    '.....W......',
    '....WWW.....',
    '....WRW.....',
    '....WWW.....',
    '...WWWWW....',
    '...RW.WR....',
    '....OOO.....',
    '....OYO.....',
    '.....O......',
  ]],

  sterretjes: [[
    '..Y.........',
    '.YYY....L...',
    '..Y....LLL..',
    '........L...',
    '............',
    '.....Y......',
    '....YYY.....',
    '.....Y......',
  ], [
    '..L.........',
    '.LLL....Y...',
    '..L....YYY..',
    '........Y...',
    '............',
    '.....L......',
    '....LLL.....',
    '.....L......',
  ]],

  paddestoel: [[
    '............',
    '...RRRRRR...',
    '..RRWRRWRR..',
    '.RRRRRRRRRR.',
    '.RWRRRRRRWR.',
    '.RRRRRRRRRR.',
    '..WWWWWWWW..',
    '...WKWWKW...',
    '...WWWWWW...',
    '...WWWWWW...',
  ], [
    '............',
    '...RRRRRR...',
    '..RRWRRWRR..',
    '.RRRRRRRRRR.',
    '.RWRRRRRRWR.',
    '.RRRRRRRRRR.',
    '..WWWWWWWW..',
    '...WWWWWW...',
    '...WWWWWW...',
    '...WWWWWW...',
  ]],

  appel: [[
    '............',
    '......N.....',
    '.....N.G....',
    '...RRRRRR...',
    '..RRRRRRRR..',
    '..RLRRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
  ], [
    '............',
    '......N.....',
    '.....NGG....',
    '...RRRRRR...',
    '..RRRRRRRR..',
    '..RLRRRRRR..',
    '..RRRRRRRR..',
    '..RRRRRRRR..',
    '...RRRRRR...',
    '....RRRR....',
  ]],

  banaan: [[
    '............',
    '.......KK...',
    '......YYYY..',
    '.....YYYY...',
    '....YYYY....',
    '...YYYY.....',
    '..YYYY......',
    '..YYY.......',
    '..YYYY......',
    '...YYYY.....',
    '....YYY.....',
  ]],
};
